/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        cream: '#FCF1DF',
        burgundy: '#5B191B',
        gold: '#CE973D',
      },
      fontFamily: {
        'special-elite': ['Special Elite', 'system-ui'],
        'montserrat': ['Montserrat', 'sans-serif'],
        'lato': ['Lato', 'sans-serif'],
        'zalando': ['Zalando Sans Expanded', 'sans-serif'],
      },
      spacing: {
        'safe-top': 'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left': 'env(safe-area-inset-left)',
        'safe-right': 'env(safe-area-inset-right)',
        '3xs': 'var(--space-3xs)',
        '2xs': 'var(--space-2xs)',
        'xs': 'var(--space-xs)',
        's': 'var(--space-s)',
        'm': 'var(--space-m)',
        'l': 'var(--space-l)',
        'xl': 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        '3xl': 'var(--space-3xl)',
      },
      fontSize: {
        'fluid-xs': ['var(--text-xs)', { lineHeight: '1.5' }],
        'fluid-sm': ['var(--text-sm)', { lineHeight: '1.5' }],
        'fluid-base': ['var(--text-base)', { lineHeight: '1.5' }],
        'fluid-lg': ['var(--text-lg)', { lineHeight: '1.5' }],
        'fluid-xl': ['var(--text-xl)', { lineHeight: '1.4' }],
        'fluid-2xl': ['var(--text-2xl)', { lineHeight: '1.3' }],
        'fluid-3xl': ['var(--text-3xl)', { lineHeight: '1.2' }],
        'fluid-4xl': ['var(--text-4xl)', { lineHeight: '1.1' }],
        'fluid-5xl': ['var(--text-5xl)', { lineHeight: '1' }],
        'fluid-6xl': ['var(--text-6xl)', { lineHeight: '1' }],
        'xs': ['clamp(0.75rem, 0.71rem + 0.22vw, 0.88rem)', { lineHeight: '1.5' }],
        'sm': ['clamp(0.88rem, 0.83rem + 0.22vw, 1rem)', { lineHeight: '1.5' }],
        'base': ['clamp(1rem, 0.96rem + 0.22vw, 1.13rem)', { lineHeight: '1.5' }],
        'lg': ['clamp(1.13rem, 1.08rem + 0.22vw, 1.25rem)', { lineHeight: '1.5' }],
        'xl': ['clamp(1.25rem, 1.18rem + 0.33vw, 1.44rem)', { lineHeight: '1.4' }],
        '2xl': ['clamp(1.5rem, 1.39rem + 0.54vw, 1.81rem)', { lineHeight: '1.3' }],
        '3xl': ['clamp(1.88rem, 1.71rem + 0.87vw, 2.38rem)', { lineHeight: '1.2' }],
        '4xl': ['clamp(2.25rem, 2.03rem + 1.09vw, 2.88rem)', { lineHeight: '1.1' }],
        '5xl': ['clamp(3rem, 2.65rem + 1.74vw, 4rem)', { lineHeight: '1' }],
        '6xl': ['clamp(3.75rem, 3.18rem + 2.83vw, 5.5rem)', { lineHeight: '1' }],
      },
      minHeight: {
        'touch': '44px',
        'screen-safe': 'calc(100vh - env(safe-area-inset-top) - env(safe-area-inset-bottom))',
        'screen-dynamic': '100dvh',
      },
      minWidth: {
        'touch': '44px',
      },
      maxWidth: {
        'readable': '65ch',
        'container': '1400px',
      },
    },
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      'tall': { 'raw': '(min-height: 800px)' },
      'short': { 'raw': '(max-height: 700px)' },
    },
    container: {
      center: true,
      padding: {
        DEFAULT: 'clamp(1rem, 5vw, 2rem)',
        sm: 'clamp(1rem, 5vw, 2rem)',
        lg: 'clamp(2rem, 5vw, 4rem)',
        xl: 'clamp(2rem, 5vw, 6rem)',
        '2xl': 'clamp(2rem, 5vw, 8rem)',
      },
    },
  },
  plugins: [],
};